version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vaultpay-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-vaultpay}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaultpay-api
    ports:
      - "8081:8080"
    environment:
      # Sobrescreve a URL do banco para apontar para o container do banco de dados (serviço 'db')
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-vaultpay}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
