ALTER TABLE transacoes
ADD COLUNM tipo VARCHAR(50) NOT NULL DEFAULT 'TRANSFERENCIA';

ALTER TABLE transacoes
    ADD COLUNM status VARCHAR(50) NOT NULL DEFAULT 'CONCLUIDA';

ALTER TABLE transacoes ALTER COLUMN tipo DROP DEFAULT;
ALTER TABLE transacoes ALTER COLUMN status DROP DEFAULT;
